# Generated by Django 5.0.3 on 2024-03-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_projects_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='user',
            new_name='user_id',
        ),
    ]
